# Generated by Django 3.2.5 on 2021-08-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_data', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Temperature')),
                ('temp_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temperature',
                'verbose_name_plural': 'Temperatures',
            },
        ),
    ]
