# Generated by Django 3.2.5 on 2021-08-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_temphistory_temp_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphistory',
            name='temp_date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
