# Generated by Django 3.2.5 on 2021-08-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_temphistory_temp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphistory',
            name='temp_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
