# Generated by Django 3.2.5 on 2021-08-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_temphistory_temp_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_limit', models.FloatField(default=20.0, verbose_name='Temperature limit')),
                ('temp_offset', models.FloatField(default=1.0, verbose_name='Temperature offset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
