# Generated by Django 3.2.5 on 2021-08-02 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
    ]
